/* Automatically generated macros for extended functionality */
#ifndef EXTENDED_FUNCTIONALITY_MACROS_USER_H
#define EXTENDED_FUNCTIONALITY_MACROS_USER_H
#define ENABLE_VERBOSE_LOGGING 1
#define ENABLE_IDENTITY_MANAGER 1
#define ENABLE_COMMAND_SEQUENCE 1
#define ENABLE_GEOLOCATION_FILTER 1
#define ENABLE_TOR_MONITOR 1
#define ENABLE_CIRCUIT_ASSESSMENT 1
#define ENABLE_CUSTOM_ROUTING 1
#define ENABLE_PACKET_CAPTURER 1
#endif /* EXTENDED_FUNCTIONALITY_MACROS_USER_H */
